### ISSUE TITLE
Can not use in local?

### ISSUE THREAD

**Issue by pgw00k** [AhmadIbrahiim/Website-downloader#13]
Hello,guys,
i clone the repo and run `npm install` to install packages success.

then i run `npm start`, all look perfect,but when i use chrome to vist `127.0.0.1:3000` i always get **Total Downloaded file: 0**.

After that,the page looks block on comperssing and return nothing

**Comment by marcchew** [comment]
works for me see whether theres a 403 error by running wget --mirror --convert-links --adjust-extension --page-requisites --no-parent --no-if-modified-since "your site here"
