### ISSUE TITLE
compress is getting a lot of time and it not working

### ISSUE THREAD

**Issue by abobakr2007** [AhmadIbrahiim/Website-downloader#32]

**Comment by AhmadIbrahiim** [comment]
Could you please add site name ?

**Comment by Locksdsc** [comment]
> Could you please add site name ?

impots.gouv.fr and http://eeerik.com/

**Comment by sabatale** [comment]
Make sure you installed wget.exe first.

**Comment by blockiyt** [comment]
just want to mention that the compressing tokk more than 40 gb of my storage, and wasnt event finished. I dont think that this should happen, right?
