### ISSUE TITLE
The demo of this tool gives an error

### ISSUE THREAD

**Issue by arminamirinasab** [AhmadIbrahiim/Website-downloader#45]
Hello, thank you very much for developing this tool, I really wanted to use this tool, but the demo tool does not load

**Comment by AhmadIbrahiim** [comment]
Should be working now : https://website-downloader.onrender.com

**Comment by arminamirinasab** [comment]
Yes, I tested it and it was ok, but it does not provide good results for WordPress sites, thank you for your follow up
