### ISSUE TITLE
Stuck at Last

### ISSUE THREAD

**Issue by fasih4444** [AhmadIbrahiim/Website-downloader#5]
It stuck their:
`> ebsite-downloader@0.0.0 start C:\Users\Fasih4444\Website-downloader
> node ./bin/www`

**Comment by AhmadIbrahiim** [comment]
@fasih4444 What is the error you are getting?

**Comment by fasih4444** [comment]
![image](https://user-images.githubusercontent.com/69955157/100094401-c91de700-2e7a-11eb-9125-5179d81f7e5e.png)
It stuck here.

Your environment has been set up for using Node.js 14.15.1 (ia32) and npm.

C:\Users\SaM>cd Website-downloader

C:\Users\SaM\Website-downloader>npm install
added 157 packages from 134 contributors and audited 159 packages in 10.813s
found 5 vulnerabilities (1 low, 1 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\SaM\Website-downloader>npm start

> website-downloader@0.0.0 start C:\Users\SaM\Website-downloader
> node ./bin/www

**Comment by fasih4444** [comment]
Windows 10

**Comment by BRAVO68WEB** [comment]
Thats it

After doing,

```
npm start
```

Now visit http://localhost:3000/ to use the app
