### ISSUE TITLE
Website need to upgrade!

### ISSUE THREAD

**Issue by priyankarpal** [AhmadIbrahiim/Website-downloader#54]
I just changed the CSS code.

![Screenshot from 2023-01-26 11-08-00](https://user-images.githubusercontent.com/88102392/214766427-19944f80-1fcb-48df-934d-6229b5339781.png)

**Comment by AhmadIbrahiim** [comment]
I think this Index.html is not used anyway!

**Comment by tusarkhan800** [comment]
yes
