### ISSUE TITLE
The website cannot be opened, and local deployment has also failed

### ISSUE THREAD

**Issue by yokiweb** [AhmadIbrahiim/Website-downloader#76]
### The website cannot be opened, and local deployment has also failed....

**Comment by alexanderroidl** [comment]
I opened a Pull Request for the local website's startup just now: https://github.com/AhmadIbrahiim/Website-downloader/pull/77

You can use my fork's branch before the PR will be merged: 
```
$ git clone git@github.com:alexanderroidl/website-downloader.git
$ cd website-downloader
$ git checkout fix/server-startup
$ npm run start
```

**Comment by alexanderroidl** [comment]
@yokiweb The local startup should be fixed now.
